# Generated by Django 4.2.10 on 2024-02-29 21:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedLink',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.JSONField()),
                ('url', models.URLField(db_index=True, max_length=512, verbose_name='URL')),
                ('text', models.TextField(blank=True, null=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('campaign', models.CharField(blank=True, max_length=50, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_links', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('ordering', 'url'),
                'unique_together': {('content_type', 'object_id', 'text', 'url', 'campaign')},
            },
        ),
        migrations.CreateModel(
            name='TrackedLinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.JSONField(null=True)),
                ('profile_hash', models.CharField(editable=False, max_length=64)),
                ('clicks', models.PositiveIntegerField(default=0, editable=False)),
                ('last_clicked', models.DateTimeField(editable=False)),
                ('medium', models.CharField(editable=False, max_length=30, null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='analytics.trackedlink')),
            ],
            options={
                'db_table': 'analytics_trackedlink_click',
                'ordering': ('-last_clicked',),
                'get_latest_by': 'last_clicked',
                'unique_together': {('user_id', 'profile_hash', 'link')},
            },
        ),
    ]
