# Generated by Django 4.2.10 on 2024-02-29 17:49

from django.db import migrations, models
import easy_thumbnails.fields
import markdownx.models
import morningcreative.podcast.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('published', models.DateField()),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('thumbnail', easy_thumbnails.fields.ThumbnailerImageField(max_length=255, upload_to=morningcreative.podcast.models.Episode.upload_thumbnail)),
                ('poster', easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=255, null=True, upload_to=morningcreative.podcast.models.Episode.upload_poster)),
                ('oembed', models.URLField(blank=True, max_length=255, null=True, verbose_name='oEmbed URL')),
                ('remote_id', models.CharField(editable=False, max_length=255, verbose_name='remote ID')),
                ('body', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-published',),
                'get_latest_by': 'published',
            },
        ),
    ]
