# Generated by Django 4.2.10 on 2024-02-29 17:51

from django.db import migrations, models
import easy_thumbnails.fields
import markdownx.models
import morningcreative.pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('headline', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('header', easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=255, null=True, upload_to=morningcreative.pages.models.Page.upload_header)),
                ('oembed', models.URLField(blank=True, max_length=255, null=True, verbose_name='oEmbed URL')),
                ('body', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('menu_visibility', models.BooleanField(default=True)),
                ('menu_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO description')),
            ],
            options={
                'ordering': ('menu_order',),
            },
        ),
    ]
